# config.yaml

# ---- General Settings ----
output_settings:
  directory: "output"
  filename: "master_grid.npy"

# ---- Grid Assembly Parameters ----
grid_params:
  master_shape: [100, 100, 100]
  block_size: 10
  tiling_probability: 0.7 # Chance to place a patterned block vs. random background

# ---- Final Noise Applied to the Whole Grid ----
final_noise:
  type: "simplex"
  strength: 0.7
  scale: 30.0
  octaves: 2

# ---- Pool of Patterns to Build From ----
# The factory will randomly select from this list to tile the grid.
pattern_pool:
  - name: "straight_x"
    type: "straight"
    params:
      direction: [1, 0, 0]
    # This pattern has no noise applied
    
  - name: "straight_y_noisy"
    type: "straight"
    params:
      direction: [0, 1, 0]
    noise: # Apply random noise to this pattern
      type: "random"
      level: 0.4
      
  - name: "bending"
    type: "bending"
    params: {} # Bending pattern requires no extra parameters

  - name: "fanning_noisy"
    type: "fanning"
    params: {}
    noise: # Apply random noise to this pattern
      type: "random"
      level: 0.5